### ISSUE TITLE
Bug: Translating Drum tablature, should produce an error when the tablature is not proper

### ISSUE THREAD

**Issue by ljaypals** [joshgenat/2311_Group7#18]
**ID:** #18
**Reporter:** Lars Jaylen Palalon email: ljaypals@my.yorku.ca
**Version:** [4bb5575](https://github.com/joshgenat/2311_Group7)
**Title:** Translating Drum tablature, should produce an error when the tablature is not proper
**Platform**: Windows 10
**Reproduction:** It was found when using the sample drum tablature and duplicating some of the lines into the next part of the tablature. The tab was still able to translate even though it is not a proper tablature.

**Expected Result:** An error message telling the user that they did not implement the tablature properly

**Actual Result:**
This is what happens when the tablature input is not consistent
![Screenshot 2021-03-23 235052](https://user-images.githubusercontent.com/77308877/112252298-3a0bba80-8c33-11eb-9096-715016c1aa4b.png)
![Screenshot 2021-03-23 235103](https://user-images.githubusercontent.com/77308877/112252302-3b3ce780-8c33-11eb-8d96-da0f898e6aa6.png)

**Priority:**  Please make sure that an error message pops up when the user input of a tablature is incorrect

**Severity:** Medium to High

**Comment by Uthith18** [comment]
Hey Lars, I do not believe this should cause an error message to appear. This is because in some drum tabs, the number of rows are not consistent (I'll post an example below). 

https://www.ultimate-tabs.com/rage-against-the-machine/killing-in-the-name-drums

The reason why the number of rows may not be consistent vary, but the main reason for this is because some drum tabs decide not to include a row/instrument in a certain section if it is not played. Thank you, for your input, we may look into making a warning message pop up, instead of an error. 

- Uthith
